name: flutter_text_recognition
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.15.0
  camera: ^0.11.2
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

#* SPLASH SCREEN
flutter_native_splash:
  android: true
  fullscreen: true

  color: "#FFFFFF"
  image: images/logo.png

  android_12:
    color: "#FFFFFF"
    image: images/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

#* LAUNCHER ICON
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/foreground.png"
